version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama_service
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  
    environment:
      - OLLAMA_USE_CUDA=1  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  
              count: all
              capabilities: [gpu]

  rag-demonstrator:
    build: .
    container_name: rag-demonstrator
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_started
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434  
    volumes:
      - .:/app
    working_dir: /app
    extra_hosts:      
      - "host.docker.internal:host-gateway"
    command: streamlit run ui.py --server.port=8501 --server.address=0.0.0.0

volumes:
  ollama_data: 
